name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Use Node.js 16.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 # Use actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend && npm install
    - run: cd backend && npm test
    - run: cd frontend && npm install
    - run: cd frontend && npm test
